### ISSUE TITLE
Images support

### ISSUE THREAD

**Issue by pedroalbanese** [myussufz/html2pdf#1]
Hello,

I made a htm2pdf conversor, but I can't print images in the pdfs. What's wrong?

Thanks in advance.

**Comment by pedroalbanese** [comment]
Code 
`package main

import (
	"os"
	"log"
	"flag"
	"github.com/magicwebes/html2pdf"
)

func main() {


   var input string
   flag.StringVar(&input, "i", "", "inputfile")

   var output string
   flag.StringVar(&output, "o", "output.pdf", "outputfile")
   flag.Parse()

    if input == "" {
        flag.PrintDefaults()
        os.Exit(1)
    }

  filepath := input
  data := map[string]interface{}{
    "message": "hello", // pass data to html file
  }
  outputPath := output

  if err := html2pdf.ParseHTML(filepath, data).
    SetConfig(&html2pdf.Config{
        PageSize: html2pdf.PageSizeA4,
    }).
    ToFile(outputPath); err != nil {
      log.Println("error", err)
  }
}`

**Comment by pedroalbanese** [comment]
I understood, because the images must have full path in the html document. But test me with another error: When I pass the -i flag via Windows prompt. It works on the Linux terminal, but on Windows the following error appears:

htm2pdf -i "networth.htm"
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x110 pc=0x4c20a3]

goroutine 1 [running]:
github.com/magicwebes/html2pdf/wkhtmltopdf.(*stringOption).Set(...)
        C:/Users/0wner/go/src/github.com/magicwebes/html2pdf/wkhtmltopdf/options
.go:159
github.com/magicwebes/html2pdf.(*PDF).SetPageSize(...)
        C:/Users/0wner/go/src/github.com/magicwebes/html2pdf/html2pdf.go:121
github.com/magicwebes/html2pdf.(*PDF).SetConfig(0x11876900, 0x1185bfb0, 0x118768
e0)
        C:/Users/0wner/go/src/github.com/magicwebes/html2pdf/html2pdf.go:109 +0x
93
main.main()
        H:/PRGM/Linux/html2pdf-master/htm2pdf/htm2pdf.go:37 +0x1d8

**Comment by pedroalbanese** [comment]
I'm cannot pass input file via Windows prompt because it searches by the path with slashes.

`package main

import (
	"os"
	"log"
	"fmt"
	"flag"
	"github.com/magicwebes/html2pdf"
)

func main() {


   var input string
   flag.StringVar(&input, "i", "", "inputfile")

   var output string
   flag.StringVar(&output, "o", "output.pdf", "outputfile")
   flag.Parse()

    if input == "" {
        flag.PrintDefaults()
        os.Exit(1)
    }

    if _, err := os.Stat(input); os.IsNotExist(err) {
    fmt.Print("Error: File not found.")
    }


  filepath := input
  data := map[string]interface{}{
    "message": "hello",
  }
  outputPath := output
  if err := html2pdf.ParseHTML(filepath, data).
    SetConfig(&html2pdf.Config{
        PageSize: html2pdf.PageSizeA4,
    }).
    ToFile(outputPath); err != nil {
      log.Println("error", err)
  }
}`

**Comment by pedroalbanese** [comment]
Hello, I need your help. The program cannot find the files. I get the error:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x1 addr=0xf0 pc=0x4cd5c9]

goroutine 1 [running]:
github.com/magicwebes/html2pdf.(*PDF).SetOrientation(...)
        C:/Users/0wner/go/src/github.com/magicwebes/html2pdf/html2pdf.go:127
github.com/magicwebes/html2pdf.(*PDF).SetConfig(0x118c0880, 0x118b1f1c, 0x118b1f
00)
        C:/Users/0wner/go/src/github.com/magicwebes/html2pdf/html2pdf.go:106 +0x
59
main.main()
